server:
  port: 9094
spring:
  application:
    name: cour-order
  cloud:
    alibaba:
      seata:
        tx-service-group: cour_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    master:
      jdbc-url: jdbc:mysql://47.100.115.11:3306/courage?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    slave1:
      jdbc-url: jdbc:mysql://47.100.115.11:3306/courage_slave1?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
    slave2:
      jdbc-url: jdbc:mysql://47.100.115.11:3306/courage_slave2?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      type: com.zaxxer.hikari.HikariDataSource
logging:
  level:
    io:
      seata: info
