server:
  port: 9099
spring:
  application:
    name: cour-api
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
      discovery:
        server-addr: 127.0.0.1:8848
    sentinel:
      transport:
        port: 8719
        dashboard: 127.0.0.1:8080

dubbo:
  scan:
    base-packages: com.muyi.courage.api.service
  protocols:
    dubbo:
      name: dubbo
      port: -1
  registry:
    address: zookeeper://47.100.115.11:2181
  #    address: nacos://${spring.cloud.nacos.discovery.server-addr}
  application:
    qos-enable: false

