DROP TABLE IF EXISTS `sys_web_log`;

CREATE TABLE `sys_web_log` (
  `USER_NO` varchar(20) CHARACTER SET utf8 DEFAULT NULL COMMENT '用户编号',
   `METHOD` varchar(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '方法类型',
  `URL` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求地址',
  `RESULT_CODE` varchar(10) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求结果码',
  `RESULT_MSG` varchar(32) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求结果',
  `START_TIME` datetime DEFAULT NULL COMMENT '请求开始时间',
  `COST_TIME` bigint(20) DEFAULT NULL COMMENT '请求花费时间',
  `CLIENT_IP` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '客户机IP',
  `SERVER_IP` varchar(50) CHARACTER SET utf8 DEFAULT NULL COMMENT '服务器IP',
  `DESCRIPTION` varchar(200) CHARACTER SET utf8 DEFAULT NULL COMMENT '请求具体描述'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='用户操作日志表';
