server:
  port: 9093
spring:
  profiles:
    active: dev
  application:
    name: cour-oauth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
  redis:
    database: 0
    host: 47.100.115.11
    port: 6379
    password: root123
    timeout: 60000 #连接超时时间（毫秒）
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 1   # 连接池中的最小空闲连接
auth:
  accessTokenValiditySeconds: 1800
  refreshTokenValiditySeconds: 3600
redis:
  prefix: 'iCourageCloud:'

management:
  endpoints:
    web:
      exposure:
        include: "*"
