server:
  port: 9092
spring:
  application:
    name: cour-auth
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  redis:
    database: 0
    host: 47.100.115.11
    port: 6379
    password: root123
    timeout: 60000 #连接超时时间（毫秒）
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 1   # 连接池中的最小空闲连接
  datasource:
      type: com.zaxxer.hikari.HikariDataSource
      url: jdbc:mysql://47.100.115.11:3306/courage?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 10
        maximum-pool-size: 60
        idle-timeout: 30000
        validation-timeout: 3000
        connection-timeout: 60000
auth:
  accessTokenValiditySeconds: 1800
  refreshTokenValiditySeconds: 3600
redis:
  prefix: 'iCourageCloud:'
