server:
  port: 8765

#请求和响应GZIP压缩支持
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
  compression:
    request:
      enabled: true
      mime-types: text/xml,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

spring:
  application:
      name: cour-gate
  redis:
    database: 0
    host: 47.100.115.11
    port: 6379
    password: root123
    timeout: 60000 #连接超时时间（毫秒）
    lettuce:
      shutdown-timeout: 300ms #关闭超时
      pool:
        max-active: 600 # 连接池最大连接数（使用负值表示没有限制）
        max-wait: -1  # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 10  # 连接池中的最大空闲连接
        min-idle: 1   # 连接池中的最小空闲连接
  cloud:
    nacos:
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
      discovery:
        server-addr: 127.0.0.1:8848
    loadbalancer:
      ribbon:
        enabled: false
    gateway:
      default-filters:
         - DedupeResponseHeader=Access-Control-Allow-Origin
      globalcors:
         add-to-simple-url-handler-mapping: true
         corsConfigurations:
           '[/**]':
             allowed-origins: "http://localhost:8080"
             allowed-methods: "*"
             allowed-headers: "*"
             allow-credentials: true
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        # =====================================
        - id: cour-auth
          uri: lb://cour-auth
          order: 8000
          predicates:
          - RequestBody=true
          - Path=/api/auth/**
          filters:
          - StripPrefix=2
    sentinel:
      transport:
        dashboard: localhost:8080

